### POST request to create a new patient entry
POST http://<localstack-cloud-loadbalancer-endpoint>:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Deployment Test",
  "email": "deploytest@example.com",
  "address": "12 Akshar Rd",
  "dateOfBirth": "1995-01-09",
  "registeredDate": "2025-10-01"
}

###