### POST request to create a new patient entry
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Kafka bhai",
  "email": "kafkatest@example.com",
  "address": "6 Prentes St",
  "dateOfBirth": "1995-03-09",
  "registeredDate": "2024-11-28"
}

###