### PUT request to update an existing patient entry
PUT http://<localstack-cloud-loadbalancer-endpoint>:4004/api/patients/<patient-id>
Content-Type: application/json

{
  "name": "John Doe ujpd",
  "email": "john.doe@example.com",
  "address": "123 Main St",
  "dateOfBirth": "1995-09-09"
}

###